name: Release

on:
  push:
    tags:
      - "v*"  # Triggers when you push a tag like "v1.0.0"

jobs:
  release:
    name: Build and Release Binaries
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21  # Change this if you're using a different Go version

      - name: Build for Linux
        run: GOOS=linux GOARCH=amd64 go build -o spwd-linux

      - name: Build for Windows
        run: GOOS=windows GOARCH=amd64 go build -o spwd-windows.exe

      - name: Build for MacOS (Intel)
        run: GOOS=darwin GOARCH=amd64 go build -o spwd-macos

      - name: Build for MacOS (Apple Silicon M1/M2)
        run: GOOS=darwin GOARCH=arm64 go build -o spwd-macos-arm64

      - name: Generate Release Notes
        run: |
          echo "## Changelog" > release_notes.md
          echo "" >> release_notes.md
          git log $(git describe --tags --abbrev=0)..HEAD --oneline >> release_notes.md

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            spwd-linux
            spwd-windows.exe
            spwd-macos
            spwd-macos-arm64
          body_path: release_notes.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
